version: '3.8'

networks:
  dickens-network:
    driver: bridge

services:
  temporal:
    image: temporalio/auto-setup:latest
    container_name: dickens-temporal
    ports:  
      - 7233:7233
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PWD=${POSTGRES_PASSWORD}
      - POSTGRES_SEEDS=dickens-postgres
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    healthcheck:
      test: [ "CMD-SHELL", "tctl --ad temporal:7233 cluster health | grep SERVING" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./docker/temporal/config:/etc/temporal/config/dynamicconfig
    depends_on:
      - postgres
    networks:
      - dickens-network

  postgres:
    image: postgres:13
    container_name: dickens-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432
    volumes:
      - /var/lib/postgresql/data
    networks:
      - dickens-network

  server:
    build:
      context: ./server
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: dickens-server
    ports:
      - "8080:8080"
    depends_on:
      temporal:
        condition: service_healthy
    environment:
      - QUARKUS_TEMPORAL_CONNECTION_TARGET=temporal:7233
    networks:
      - dickens-network

  temporal-web:
    image: temporalio/web:latest
    container_name: dickens-temporal-web
    ports:
      - "8088:8088" # Temporal Web UI
    depends_on:
      temporal:
        condition: service_healthy
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
    networks:
      - dickens-network

  bluesky:
    build:
      context: ./clients/bluesky
      container_name: dickens-bluesky
    depends_on:
      temporal:
        condition: service_healthy
    environment:
      TEMPORAL_SERVICE_ADDRESS: temporal:7233
    networks:
      - dickens-network

  twitter:
    build:
      context: ./clients/twitter
      container_name: dickens-twitter
      dockerfile: Dockerfile
    environment:
      - TEMPORAL_HOST=temporal:7233
      # Add Twitter API credentials when implementing actual integration
      # - TWITTER_API_KEY=your_api_key
      # - TWITTER_API_SECRET=your_api_secret
      # - TWITTER_ACCESS_TOKEN=your_access_token
      # - TWITTER_ACCESS_SECRET=your_access_secret
    depends_on:
      temporal:
        condition: service_healthy
    networks:
      - dickens-network
    

  linkedin:
    build:
      context: ./clients/linkedin
      container_name: dickens-linkedin
      dockerfile: Dockerfile
    environment:
      - TEMPORAL_HOST=temporal:7233
      # Add LinkedIn API credentials when implementing actual integration
      # - LINKEDIN_CLIENT_ID=your_client_id
      # - LINKEDIN_CLIENT_SECRET=your_client_secret
      # - LINKEDIN_ACCESS_TOKEN=your_access_token
    depends_on:
      temporal:
        condition: service_healthy
    networks:
      - dickens-network
    

volumes:
  dickens-postgres-data:
